# Generated by Django 4.2.7 on 2023-11-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Draft', 'd'), ('Published', 'p')], default='d', max_length=15),
        ),
    ]
